#!/bin/bash

if [ "$EUID" -ne 0 ]; then
	command -v sudo >/dev/null 2>&1 && echo "This script must be run as root. Use 'sudo' or run it as root."
	command -v doas >/dev/null 2>&1 && echo "This script must be run as root. Use 'doas' or run it as root."
	exit 1
fi

install() {
    if [ $# -lt 2 ]; then
	echo "Usage: apt-src install <package>"
        exit 1
    fi
	[[ -d /tmp/apt-src ]] || mkdir /tmp/apt-src
	cd /tmp/apt-src
	apt source install --build "$2" || apt build-dep -yy "$2" && apt source install --build "$2" && dpkg -i "$2"*.deb && echo -e "Package: $2 installed." || echo -e >&2 "Error: $2 is not installed."
}

case "$1" in
    install)
        install "$@"
        ;;
    *)
	echo "Usage: apt-src install <package>"
	echo "Example: apt-src install hello"
	exit 1
        ;;
esac

exit 0
