#!/bin/bash

set -e

command -v dpkg >/dev/null 2>&1 || { echo >&2 "This script only works on Debian."; exit 1; }

install() {
    if [ $# -ne 2 ]; then
	echo -e "Usage: apt-src install <package>"
        exit 1
    fi
	[[ -d /tmp/apt-src ]] || mkdir /tmp/apt-src
	cd /tmp/apt-src
	apt source --build "$2" || sudo apt build-dep -yy "$2" && apt source --build "$2" && sudo dpkg -i "$2"*.deb && echo -e "Package: $2 is installed." || echo -e >&2 "Error: Package $2 is not installed."
}

case "$1" in
    install)
        install "$@"
        ;;
    *)
	[[ -d /tmp/apt-src ]] || mkdir /tmp/apt-src
	cd /tmp/apt-src
	apt source "$1" && sudo apt build-dep -yy "$1" && echo -e "Package: $1 is downloaded and located at /tmp/apt-src/ ." || echo -e >&2 "Error: Package $1 is not downloaded."
	echo -e "Usage: apt-src install $1"
        ;;
esac
