#!/bin/bash

command -v dpkg >/dev/null 2>&1 || { echo >&2 "This script only works on Debian."; exit 1; }

install() {
    if [ $# -lt 2 ]; then
	echo "Usage: apt-src install <package>"
        exit 1
    fi
	[[ -d /tmp/apt-src ]] || mkdir /tmp/apt-src
	cd /tmp/apt-src
	apt source install --build "$2" || sudo apt build-dep -yy "$2" && apt source install --build "$2" && sudo dpkg -i "$2"*.deb && echo -e "Package: $2 installed." || echo -e >&2 "Error: $2 is not installed."
}

case "$1" in
    install)
        install "$@"
        ;;
    *)
	echo "Usage: apt-src install <package>"
	echo "Example: apt-src install hello"
	exit 1
        ;;
esac

exit
